dist_man1_MANS=

if BUILD_ORDEXCOIND
  dist_man1_MANS+=ordexcoind.1
endif

if ENABLE_QT
  dist_man1_MANS+=ordexcoin-qt.1
endif

if BUILD_ORDEXCOIN_CLI
  dist_man1_MANS+=ordexcoin-cli.1
endif

if BUILD_ORDEXCOIN_TX
  dist_man1_MANS+=ordexcoin-tx.1
endif

if BUILD_ORDEXCOIN_UTIL
  dist_man1_MANS+=ordexcoin-util.1
endif

if ENABLE_WALLET
if BUILD_ORDEXCOIN_WALLET
  dist_man1_MANS+=ordexcoin-wallet.1
endif
endif
